import { makeRequest } from "./utils.js"

const sep = ", "
makeRequest("select-city", {})
    .then(res => res.json())
    .then(res => console.log("CITY:", res.res.result.join(sep)))
makeRequest("select-method", {})
    .then(res => res.json())
    .then(res => console.log("METHOD:", res.res.result.join(sep)))
makeRequest("select-shop", {})
    .then(res => res.json())
    .then(res => console.log("SHOP:", res.res.result.join(sep)))
makeRequest("select-category", {})
    .then(res => res.json())
    .then(res => console.log("CATEGORY:", res.res.result.join(sep)))
makeRequest("select-item", {})
    .then(res => res.json())
    .then(res => console.log("ITEM:", res.res.result.join(sep)))
makeRequest("select-payment", { "monthDate": "now" })
    .then(res => res.json())
    .then(res => console.log("PAYMENT:", res.res.result.join(sep)))
makeRequest("select-detailorder", { "paymentId": 1 })
    .then(res => res.json())
    .then(res => console.log("DETAILORDER:", res.res.result.join(sep)))
